### ISSUE TITLE
Duplicate symbol '_kOrientationKey' (MoPub-Vungle-Adapters)

### ISSUE THREAD

**Issue by dylancom** [mopub/mopub-ios-mediation#265]
1. **What is the issue?**
    When upgrading from 6.4.6.0 to 6.5.2.0 building in Xcode fails with the error: duplicate symbol '_kOrientationKey'.

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Platform** (*Android, iOS, Unity*)
        iOS
    * **MoPub SDK Version**
        5.11.0
    * **Mediation SDK Name & Version**
        VungleSDK-iOS 6.5.2
    * **Mediation Adapter Version**
        MoPub-Vungle-Adapters 6.5.2.0
    * **Steps to reproduce the issue** (include integration steps if not standard)
        Upgrade pod 'MoPub-Vungle-Adapters' from '6.4.6.0' to '6.5.2.0' and run the project in Xcode.
    * **Observed behavior**
        duplicate symbol '_kOrientationKey' in: /Users/***User***/Apps/***App***/ios/Pods/VungleSDK-iOS/VungleSDK.framework/VungleSDK(VungleUtil.o)
    /Users/***User***/Library/Developer/Xcode/DerivedData/***App***-ftmlzqpueslsnkekappsnfzybprh/Build/Products/Debug-iphonesimulator/mopub-ios-sdk/libmopub-ios-sdk.a(MPAdServerKeys.o)
1 duplicate symbol for architecture x86_64
    * **Expected behavior** (if known)
        0 errors.

**Comment by amacymind** [comment]
@dylancom How you resolved this issue? Actually i am facing same issue.

**Comment by dylancom** [comment]
@amacymind I haven't, but it's related to the VungleSDK, not the adapter.

**Comment by amacymind** [comment]
You mean if i remove VungleSDK then issue not occur?

**Comment by dylancom** [comment]
@amacymind No I mean that they have to solve it in the VungleSDK not in this repo. That's why I closed the issue here.
